### ISSUE TITLE
Issues building project

### ISSUE THREAD

**Issue by Tjoppetjam** [SvenEV/Shader-Explorer-For-Xenko#1]
Hi!

First off, cool project! It looks like a very handy tool when learning XKSL!

However, the VS solution contains a unavailable dependency/project (AurelienRibon.Ui.SyntaxHighlightBox.2.0.2). I've removed the unavailable project and added it as a NuGet package:
```
<?xml version="1.0" encoding="utf-8"?>
<packages>
  <package id="AurelienRibon.Ui.SyntaxHighlightBox" version="2.0.2" targetFramework="net452" />
  <package id="CommonServiceLocator" version="1.3" targetFramework="net452" />
  <package id="MvvmLightLibs" version="5.3.0.0" targetFramework="net452" />
</packages>
```
After that, the project will build, but there's a KeyNotFoundException when getting the XKSL highlighter (in MainWindow.xaml.cs:16):
```
codeView.CurrentHighlighter = HighlighterManager.Instance.Highlighters["XKSL"];
```

I'm guessing the highlight stuff is in the unavailable project.

Could you include the AurenlienRibon.Ui.SyntaxHighlighBox project, or include the highlight files?

**Comment by SvenEV** [comment]
Oops, I forgot to add that project, thank you for pointing that out. As you have seen, adding the NuGet package does not work because it does not include the XKSL definition. I have added the syntax highlighter project and it should compile now.
